name: Demo
on:
  push:
    branches:
      - main

jobs:
  demo:
    permissions:
      # This is required or tbot will not be able to authenticate
      id-token: write
      contents: read
    name: demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup teleport
        uses: gravitational/teleport-actions/setup@v1
        with:
          # version must be specified, and exclude the "v" prefix.
          # check https://goteleport.com/download/ for valid releases.
             version: 11.0.1
      - name: Fetch credentials a
        run: ./tbot start -d --join-method=github --token=github-bot-2 --auth-server=teleport-11-ent.asteroid.earth:443 --oneshot --destination-dir=./certs --data-dir=./data
      - run: ls ./certs
      - name: List nodes
        run: ./tsh -i ./certs/identity --proxy teleport-11-ent.asteroid.earth:443 ls
   
